# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-19 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
