# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-19 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0002_auto_20170519_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_inicio',
        ),
    ]
