# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-19 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0003_auto_20170519_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
