# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-19 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0004_auto_20170519_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='hora_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
