# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-19 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0005_auto_20170519_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='hora_inicio',
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
